### ISSUE TITLE
lab requires no work

### ISSUE THREAD

**Issue by kvignali** [learn-co-curriculum/my-select#10]
The my_select.rb file is already fully implemented when I cloned the file and passes all tests immediately without me doing anything. Also, I do not know if this is an issue or not but I had to run 'bundle install' to update rspec. Easy enough to do, but never had to do so in any of the other exercises so far / just a heads up.

**Comment by AnnJohn** [comment]
added note to run 'bundle install' and updated the lib file so that all tests fail.
