### ISSUE TITLE
Last 3 Links are Broken

### ISSUE THREAD

**Issue by walkingalchemy** [learn-co-curriculum/my-select#11]
At the end of the Readme:

http://ruby.about.com/od/beginningruby/a/Block-Parameters-And-Yielding.htm
http://blog.codahale.com/2005/11/24/a-ruby-howto-writing-a-method-that-uses-code-blocks/
http://www.reactive.io/tips/2008/12/21/understanding-ruby-blocks-procs-and-lambdas/

**Comment by morgvanny** [comment]
I believe this is fixed now. Thank you for letting us know!
